module.exports = [
	{
		id: "gRB9aGkGQItzXsNsSeMep",
		item_name: "Salary",
		amount: 5000,
		date: "2024-07-01",
		merchant: "Employer",
		category: "Income",
		isDeposit: true,
	},
	{
		id: "zRB4aGkGQItzXsNsSlMaf",
		item_name: "Groceries",
		amount: 150,
		date: "2024-07-02",
		merchant: "Grocery Store",
		category: "Food",
		isDeposit: false,
	},
	{
		id: "3VfPSnNKpXvI9X_PbWZ0p",
		item_name: "Rent",
		amount: 1200,
		date: "2024-07-03",
		merchant: "Landlord",
		category: "Housing",
		isDeposit: true,
	},
	{
		id: "2VfPSnNepXvI9X_PbWf0p",
		item_name: "Cat Food",
		amount: 40,
		date: "2024-07-04",
		merchant: "Pet Store",
		category: "Pets",
		isDeposit: false,
	},
	{
		id: "5VfPSnNKpXvI9X_PbWZ0p",
		item_name: "Savings Deposit",
		amount: 500,
		date: "2024-07-05",
		merchant: "Bank",
		category: "Savings",
		isDeposit: false,
	},
];
